import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        ore: {
          black: 'var(--ore-black)',
          bg: 'var(--ore-bg)',
          'bg-raised': 'var(--ore-bg-raised)',
          surface: 'var(--ore-surface)',
          'surface-2': 'var(--ore-surface-2)',
          'surface-3': 'var(--ore-surface-3)',
          'border-dim': 'var(--ore-border-dim)',
          border: 'var(--ore-border)',
          'border-strong': 'var(--ore-border-strong)',
          'bevel-light': 'var(--ore-bevel-light)',
          text: 'var(--ore-text)',
          'text-bright': 'var(--ore-text-bright)',
          'text-muted': 'var(--ore-text-muted)',
          'text-dim': 'var(--ore-text-dim)',
        },
        green: {
          DEFAULT: 'var(--ore-green)',
          bright: 'var(--ore-green-bright)',
          face: 'var(--ore-green-face)',
          shadow: 'var(--ore-green-shadow)',
        },
        blue: {
          DEFAULT: 'var(--ore-blue)',
          bright: 'var(--ore-blue-bright)',
          face: 'var(--ore-blue-face)',
          shadow: 'var(--ore-blue-shadow)',
        },
        gold: {
          DEFAULT: 'var(--ore-gold)',
          bright: 'var(--ore-gold-bright)',
          face: 'var(--ore-gold-face)',
          shadow: 'var(--ore-gold-shadow)',
        },
        red: {
          DEFAULT: 'var(--ore-red)',
          bright: 'var(--ore-red-bright)',
          face: 'var(--ore-red-face)',
          shadow: 'var(--ore-red-shadow)',
        },
        block: {
          iron: 'var(--block-iron)',
          'iron-light': 'var(--block-iron-light)',
          'iron-dark': 'var(--block-iron-dark)',
          gold: 'var(--block-gold)',
          'gold-light': 'var(--block-gold-light)',
          'gold-dark': 'var(--block-gold-dark)',
          diamond: 'var(--block-diamond)',
          'diamond-light': 'var(--block-diamond-light)',
          'diamond-dark': 'var(--block-diamond-dark)',
          emerald: 'var(--block-emerald)',
          'emerald-light': 'var(--block-emerald-light)',
          'emerald-dark': 'var(--block-emerald-dark)',
        },
      },
      fontFamily: {
        display: 'var(--font-display)',
        body: 'var(--font-body)',
        mono: 'var(--font-mono)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        slot: 'var(--radius-slot)',
      },
      boxShadow: {
        panel: 'var(--shadow-panel)',
        float: 'var(--shadow-float)',
        'bevel-neutral': 'var(--bevel-neutral)',
        'bevel-neutral-pressed': 'var(--bevel-neutral-pressed)',
        'bevel-green': 'var(--bevel-green)',
        'bevel-green-pressed': 'var(--bevel-green-pressed)',
        'bevel-blue': 'var(--bevel-blue)',
        'bevel-gold': 'var(--bevel-gold)',
        'bevel-red': 'var(--bevel-red)',
        'inset-well': 'var(--inset-well)',
        'inset-slot': 'var(--inset-slot)',
        'glow-green': 'var(--glow-green)',
        'glow-blue': 'var(--glow-blue)',
      },
      transitionTimingFunction: {
        out: 'var(--ease-out)',
        press: 'var(--ease-press)',
      },
      maxWidth: {
        container: 'var(--container-max)',
      },
    },
  },
  plugins: [],
} satisfies Config
